const CONFIG_LAST_UPDATE_DATA_TIME = 'config/CONFIG_LAST_UPDATE_DATA_TIME';
const CONFIG_LAST_UPDATE_CONFIG_TIME = 'config/CONFIG_LAST_UPDATE_CONFIG_TIME';
const CONFIG_PREIOD_TIME_UPDATE_CONFIG_IN_HOUR =
    'config/CONFIG_PREIOD_TIME_UPDATE_CONFIG_IN_HOUR';
const CONFIG_PREIOD_TIME_UPDATE_DATA_IN_HOUR =
    'config/CONFIG_PREIOD_TIME_UPDATE_DATA_IN_HOUR';
const CONFIG_LAST_TIME_LOGIN = 'config/CONFIG_LAST_TIME_LOGIN';
const CONFIG_VERSION_APP = 'config/CONFIG_VERSION_APP';
const CONFIG_IS_FORCE_UPDATE = 'config/CONFIG_IS_FORCE_UPDATE';
const CONFIG_LANG = "config/CONFIG_LANG";
const CONFIG_FIRST_LOGIN = 'config/CONFIG_FIRST_LOGIN';
const CONFIG_DEVICE_ID = 'config/CONFIG_DEVICE_ID';
const CONFIG_ANDROID_VERSION = 'ANDROID_VERSION';
const CONFIG_IOS_VERSION = 'IOS_VERSION';
const CONFIG_RESET_TOKEN = 'config/CONFIG_RESET_TOKEN';
const CONFIG_IP_ADDRESS = 'config/CONFIG_IP_ADDRESS';
const CONFIG_LOCATION = 'config/CONFIG_LOCATION';
const CONFIG_THOUSAND_SEPARATOR = 'config/CONFIG_THOUSAND_SEPARATOR';
const CONFIG_DECIMAL_SEPARATOR = 'config/CONFIG_DECIMAL_SEPARATOR';
const CONFIG_REF_CODE_DEEPLINK = 'config/CONFIG_REF_CODE_DEEPLINK';
const CONFIG_NFT_SLUG_DEEPLINK = 'config/CONFIG_NFT_SLUG_DEEPLINK';
const CONFIG_USERNAME_DEEPLINK = 'config/CONFIG_USERNAME_DEEPLINK';
const CONFIG_LAST_OPEN_NOTIFICATION = 'config/CONFIG_LAST_OPEN_NOTIFICATION';
const CONFIG_SKIP_REMIND_KYC = 'config/CONFIG_REMIND_KYC';
const CONFIG_FIRST_TUTORIAL = 'config/CONFIG_FIRST_TUTORIAL';
const CONFIG_DATE_REMIND_KYC = 'config/CONFIG_DATE_REMIND_KYC';

const CONFIG_THEME_MODE = 'config/CONFIG_THEME_MODE';
const CONFIG_UUID = 'config/CONFIG_UUID';
const CONFIG_ACCESS_TOKEN = 'config/CONFIG_ACCESS_TOKEN';
const CONFIG_REFRESH_TOKEN = 'config/CONFIG_REFRESH_TOKEN';
const CONFIG_USERNAME = 'config/CONFIG_USERNAME';
const CONFIG_LAST_USERNAME = 'config/CONFIG_LAST_USERNAME';
const CONFIG_REGISTER_USERNAME = 'config/CONFIG_REGISTER_USERNAME';
const CONFIG_TOPIC = 'config/CONFIG_TOPIC';
const CONFIG_AVATAR = 'config/CONFIG_AVATAR';
const CONFIG_REFERRAL_CODE = 'config/CONFIG_REFERRAL_CODE';
const CONFIG_REFERRAL_USER = 'config/CONFIG_REFERRAL_USER';
const CONFIG_COLLECTION_DEFAULT_ID= 'config/CONFIG_COLLECTION_DEFAULT_ID';

//NFT Marketplace
const CONFIG_FIRST_JOIN_NFT = 'config/CONFIG_FIRST_JOIN_NFT';
const CONFIG_HISTORY_SEARCH = 'config/CONFIG_HISTORY_SEARCH';

const Map<String, String> MAP_CONFIGS = {
  'version_app': CONFIG_VERSION_APP,
  'is_force_update': CONFIG_IS_FORCE_UPDATE,
  'period_time_update_config_in_hour': CONFIG_PREIOD_TIME_UPDATE_CONFIG_IN_HOUR,
  'period_time_update_data_in_hour': CONFIG_PREIOD_TIME_UPDATE_DATA_IN_HOUR,
};

const Map<String, String> DEFAULT_CONFIG = {
  CONFIG_IS_FORCE_UPDATE: 'false',
  CONFIG_PREIOD_TIME_UPDATE_CONFIG_IN_HOUR: '2',
  CONFIG_PREIOD_TIME_UPDATE_DATA_IN_HOUR: '1',
  CONFIG_LAST_UPDATE_DATA_TIME: '0',
  CONFIG_LAST_UPDATE_CONFIG_TIME: '0'
};

const String BOX_CONFIG = 'BOX_CONFIG';
const String BOX_USER = 'BOX_USER';
const String BOX_SYSTEM_CONFIG = 'BOX_SYSTEM_CONFIG';

const NOTIFICATION_TYPE_NEWS = 'news';
const NOTIFICATION_TYPE_UPDATE = 'update';
const NOTIFICATION_TYPE_ACTION = 'action';
const NOTIFICATION_TYPE_EVENT = 'event';
const NOTIFICATION_TYPE_REFERRAL = 'referral';
const NOTIFICATION_TYPE_TRANSFER_REQUEST = 'transfer_request';
const NOTIFICATION_TYPE_WITHDRAW_REQUEST = 'withdraw_request';
const NOTIFICATION_TYPE_WITHDRAW_SUCCESSFUL = 'withdraw_successful';
const NOTIFICATION_TYPE_WITHDRAW_FAILED = 'withdraw_failed';
const NOTIFICATION_TYPE_LOGIN_SUCCESSFUL = 'login_successful';
const NOTIFICATION_TYPE_KYC_SUCCESSFUL = 'kyc_successful';
const NOTIFICATION_TYPE_KYC_FAILED = 'kyc_failed';
const NOTIFICATION_TYPE_DEPOSIT_SUCCESSFUL = 'deposit_successful';
const NOTIFICATION_TYPE_DEPOSIT_FAILED = 'deposit_failed';
const NOTIFICATION_TYPE_TRANSFER_FAILED = 'transfer_failed';
const NOTIFICATION_TYPE_TRANSFER_NFT = 'transfer_nft';
const NOTIFICATION_TYPE_TRANSFER_SUCCESSFUL = 'transfer_successful';
const NOTIFICATION_TYPE_FORECAST_NEW = 'forecast_new';
const NOTIFICATION_TYPE_ARTICLE = 'article';
const NOTIFICATION_TYPE_TRIGGER_NOT_KYC = 'trigger_not_kyc';
const NOTIFICATION_TYPE_TRIGGER_KYC_FAIL = 'trigger_kyc_failure';
const NOTIFICATION_TYPE_NFT_MINT_SUCCESSFUL = 'nft_mint_successful';
const NOTIFICATION_TYPE_NFT_MINT_CANCELLED = 'nft_mint_cancelled';
const NOTIFICATION_TYPE_BID_NFT_FAILED = 'bid_nft_failed';
const NOTIFICATION_TYPE_BID_NFT_SUCCESSFUL = 'bid_nft_successful';
const NOTIFICATION_TYPE_SELL_NFT_SUCCESSFUL = 'sell_nft_successful';
const NOTIFICATION_TYPE_NOTIFY_TYPE = 'notify_type';
const NOTIFICATION_TYPE_BLOCK_NFT = 'block_nft';
const NOTIFICATION_TYPE_COLLECTION_MINT_SUCCESS = 'collection_mint_success';
const NOTIFICATION_TYPE_REQUEST_CREATOR_SUCCESSFUL =
    'request_creator_successful';
const NOTIFICATION_TYPE_WITHDRAW_NFT_SUCCESS = 'withdraw_nft_success';
const NOTIFICATION_TYPE_WITHDRAW_NFT_CANCELLED = 'withdraw_nft_cancelled';
const NOTIFICATION_TYPE_TRANSFER_NFT_SUCCESSFUL = 'isFastMintful';
const NOTIFICATION_TYPE_NFT_COLLECTION_MINT_SUCCESSFUL =
    'nft_collection_mint_successful';
const REQUEST_ACCOUNT_FAILED = 'request_account_failed';
const REQUEST_ACCOUNT_SUCCESSFUL = 'request_account_successful';
const BLOG_CATEGORY_NEWS = 'goc-kien-thuc';
const BLOG_CATEGORY_ANNOUNCEMENT = 'tin-tuc';

const  CHECK_COUNT_OPEN_CODE  = 'config/count';
